Feature/#14 model cola
Doong-Ji/cola-map pull request #20
Opened 2021-06-17 15:42 UTC by dode777

## #14 

## PR 설명
- 더미 데이터를 이용해 post 시 콜라 스키마를 생성
- get 시 저장된 더미 데이터를 조회

## 변경된 내용
- 서버, DB 연결 시 콘솔에 출력되는 메시지 조금 잘 보일 수 있도록 이모지 추가
- Cola 모델 추가
- 더미 데이터 추가 및 조회

## 추가적인 정보
- Prettier에 의해서 코드 스타일이 "" 에서 '' 로 자동 변경되었습니다.
- models/user.js 에서 DeprecationWarning 오류가 발생해 구글링 후 오류 해결하였습니다.

close #14

2021-06-19 10:13 UTC, Yubron approved these changes
수고하셨습니당

2021-06-19 12:25 UTC, junh0328 requested changes
제가 리뷰단 부분에 대한 일부 수정사항이나 피드백이 필요해 보입니다! 수고하셨습니다~

2021-06-19 12:25 UTC, junh0328 commented on server/app.js
>  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
```
app.use('/api/v1/', userRouter);
```
이 부분이 userRouter와 colaRouter 두 부분을 모두 가르키고 있어서, 정리가 필요해봅입니다.

2021-06-19 12:25 UTC, junh0328 commented on server/routers/colaRouter.js
> +colaRouter.get('/get', async (req, res) => {
이렇게 될 경우에는
```
app.js 에서 

app.use('/api/v1/', userRouter); 를 만나서 userRouter로 옮겨지고,
```
를 통해서 /api/v1/get 요청이 올 경우에 실행되기는 하겠네요

과거 저의경우에는

```js
app.use('/posts', postsRouter);
app.use('/post', postRouter);
app.use('/user', userRouter);
app.use('/hashtag', hashtagRouter);
```
이런식으로 결로를 지정한 다음에 애초에 RESTAPI가 get 요청이기 때문에 '/get'을 쓰지 않고

```js
routes/postsRouter
...
router.get('/', async (req, res, next) => { ... } 와 같은 방식으로 사용하였습니다.
```
프론트에서 postsRouter에 get 요청을 보낸다고 가정한다면
프록시 설정을 아직 하지 않았을 경우
```js
axios.get('http://localhost:5000/posts')
```
와 같은 형태로 보낼 것으로 보입니다

2021-06-19 12:54 UTC, dode777 commented on server/app.js
> +const userRouter = require('./routers/colaRouter');
한번 코드를 날리고 클론해왔는데 그 때 아마 놓친 것 같습니다.
아래 코멘트와 함께 처리하겠습니다.
감사합니다!

2021-06-19 12:56 UTC, dode777 commented on server/routers/colaRouter.js
> +colaRouter.get('/get', async (req, res) => {
저 경로에 대한 정리가 조금 필요할 것 같습니다.
지금 get와 post가 요청될 수 있는 URI가 뭐가 있을까요?

2021-06-19 13:02 UTC, junh0328 commented on server/routers/colaRouter.js
> +colaRouter.get('/get', async (req, res) => {
스키마를  

```
음료 모델 (콜라,펩시)
사용자 모델 (유저 정보)
가게 모델 (음료, 사용자 정보 포함)
리뷰 모델 (유저 정보 포함)
```

제 생각에는 이 정도로 작성해도 괜찮을 것 같은데, 백엔드 분들이 원하시는 방향으로 작업해주시면 될 것 같습니다.

2021-06-19 13:03 UTC, dode777 commented on server/routers/colaRouter.js
> +colaRouter.get('/get', async (req, res) => {
홈('/')에서 get과 post 요청이 들어오니

app.js 내에서는
app.use('/', colaRouter) 이런식으로 처리하면 될 것 같고

colaRouter.js 내에서는
colaRouter.get('/uriName' async (req, res) => { }
colaRouter.post('/uriName' async (req, res) => { }

이렇게 들어가면 될 것 같은데 저기 uri 명을 어떻게 줄지 고민이 되네요

2021-06-19 13:06 UTC, dode777 commented on server/routers/colaRouter.js
> +colaRouter.get('/get', async (req, res) => {
그냥 /cola로 주는 것도 괜찮아보이네요..

2021-06-19 13:06 UTC, junh0328 commented on server/routers/colaRouter.js
> +colaRouter.get('/get', async (req, res) => {
<a href="https://github.com/junh0328/nextjs-aws-service/tree/renew/prepare/front/sagas">uri 예시</a> 해당 링크에서 user.js / post.js 아무거나 들어가셔서, ctrl + F 를 통해서 api 검색하시면 참고할만 한 uri 를 많이 작성해두었습니다

2021-06-19 13:08 UTC, junh0328 commented on server/routers/colaRouter.js
> +colaRouter.get('/get', async (req, res) => {
<a href="https://github.com/junh0328/nextjs-aws-service/tree/renew/prepare/backend/routes">back uri 예시</a> 해당 링크에는 백엔드 라우팅처리 관련 작업했던 부분입니다

2021-06-19 13:09 UTC, junh0328 commented on server/routers/colaRouter.js
> +colaRouter.get('/get', async (req, res) => {
beverage 나 category 등도 괜찮을 것 같습니다 ㅋㅋ

2021-06-19 13:11 UTC, HwanChang commented on server/routers/colaRouter.js
> +      // 더미 데이터
코드에는 더미 데이터를 직접 하드코딩 하는일이 없도록 해주세요.
이런 부분은 테스트 코드를 작성해서 검증을 할 수 있겠네요.

2021-06-19 13:19 UTC, dode777 commented on server/routers/colaRouter.js
> +colaRouter.get('/get', async (req, res) => {
나중에 음료가 추가될 것도 생각하면 cola보다는 beverage가 나을 수 있겠네요
beverage로 적용하겠습니다.

2021-06-19 13:21 UTC, dode777 commented on server/routers/colaRouter.js
> +colaRouter.get('/get', async (req, res) => {
userRouter쪽은 진수님이 작업하신 거라 어떻게 작업해야할지 잘 모르겠습니다..
나머지는 전부 수정했습니다

2021-06-19 13:24 UTC, dode777 commented on server/routers/colaRouter.js
> +colaRouter.get('/get', async (req, res) => {
스키마는 말씀해주신 내용 참고해서 작업해보겠습니다.

2021-06-19 13:24 UTC, junh0328 commented on server/routers/colaRouter.js
> +colaRouter.get('/get', async (req, res) => {
나머지 리뷰사항에 대해서 Resolve conversation 누르시면 change request는 종료될 것 같습니다 고생하셨어요~

2021-06-19 13:25 UTC, dode777 commented on server/routers/colaRouter.js
> +      // 더미 데이터
테스트 코드를 접해본 적이 없어서
어떻게 접근해야할지 잘 모르겠는데 참고할만한 자료가 있을까요?

2021-06-19 13:27 UTC, dode777 commented on server/routers/colaRouter.js
> +colaRouter.get('/get', async (req, res) => {
감사합니다.

2021-06-19 13:31 UTC, dode777 commented on server/routers/colaRouter.js
> +      // 더미 데이터
저희가 더미데이터를 통해서 메인 지도에 데이터를 뿌려보고 싶은 상황인데
이런 상황에도 더미데이터 하드코딩은 적합하지 않은가요?

2021-06-19 13:34 UTC, dode777 commented on server/routers/colaRouter.js
> +      // 더미 데이터
더미데이터를 작성하는 대신 테스트 코드를 검증하고 더미데이터를 빼라는 말씀이시군요
준희님과 대화해보다가 이해했습니다!

2021-06-23 01:51 UTC, Yubron approved these changes

2021-06-23 01:53 UTC, junh0328 approved these changes

2021-06-23 04:34 UTC, merged