Feature/#38 schema & router
Doong-Ji/cola-map pull request #39
Opened 2021-07-13 01:48 UTC by dode777

## #38 

## PR 설명
- User 스키마를 수정하고 유저 목록 조회 및 삭제 라우터 추가

## 변경된 내용
- User 스키마 - kakaoMail, avatarUrl 필드 추가
- User 스웨거 작성
- README.md - API, 변수명 설명 삭제 및 '서버, DB 정상 실행 시 출력 메시지' 사진 추가
- prettierIgnore 파일 추가 - server 폴더 내 md 파일 무시

## 추가적인 정보
- Rebase 시도하다가 작업물이 중간에 날아가서 빠진 것이 있을 수도 있습니다..

close #38

2021-07-13 06:27 UTC, junh0328 requested changes

2021-07-13 06:27 UTC, junh0328 commented on server/models/user.js
> +    default: '../default_avatar.jpg',
서버에서 default: '../default_avatar.jpg'와 같이 상대 경로로 저장하면, 프론트에서 전달받을 수 있나요?

2021-07-13 06:27 UTC, junh0328 commented on server/routers/userRouter.js
> +        kakaoMail = req.query.kakaoMail;
어차피 전부 kakao를 통해서 받아오는 부분이기도 하니, 통일하는 방법도 있을 것 같습니다
```
카카오에서는
{
    profile_nickname : '', 
    profile_image: '', 
    account_email: '',
}
```
와 같은 프로퍼티 명으로 받아오긴 합니다. 저도 추가적으로 찾아 봐야 겠네요

2021-07-13 06:27 UTC, junh0328 commented on server/routers/userRouter.js
> +    res.send({ token: token });
이렇게 보내게 되면 넘어오는 token이 access_token/ refresh_token 중 access_token 인가요?

2021-07-13 06:29 UTC, dode777 commented on server/routers/userRouter.js
> +    res.send({ token: token });
음.. 제가 작업한 게 아니고 진수님이 작업하신 거에 prettier가 적용됐네요
저도 잘 모르겠어서 진수님 태그해볼게요
@Yubron

2021-07-13 06:30 UTC, dode777 commented on server/routers/userRouter.js
> +        kakaoMail = req.query.kakaoMail;
네 저도 아까 준희님이 보내주신 거 보고 그게 좋겠다고 생각이 들었네요
수정 작업하겠습니당

2021-07-13 06:31 UTC, dode777 commented on server/models/user.js
> +    default: '../default_avatar.jpg',
저도 이것 때문에 아까 슬랙에 여쭤본 거긴한데... 상대 경로가 될지 모르겠습니다.
근데 아까 얘기했던 것처럼 사진이 필수 항목으로 가져와지면 default 값은 필요가 없을 것 같습니다

2021-07-13 06:40 UTC, junh0328 commented on server/models/user.js
> +    default: '../default_avatar.jpg',
그 사용자가 만약 프로필 사진 설정을 안해놓은 경우에는 카카오톡 기본 이미지(파란거)가 넘어오는 걸로 확인했습니다 ㅋㅋ

2021-07-13 23:44 UTC, dode777 commented on server/models/user.js
> +    default: '../default_avatar.jpg',
그렇죠? ㅠㅠ 기본 이미지 구해온 건 쓸 곳이 없을 것 같네요ㅠㅠ ㅋㅋ

2021-07-14 00:40 UTC, dode777 commented
- [ ] 사진 필드 default 값 삭제  

- [ ] User 모델 키 값을 카카오 로그인 시 가져오는 변수명과 통일  

- [ ] /user/login POST 시 `uniqId`, `profile_nickname`, `profile_image`, `account_email` 값을 body에서 가져오도록 변경  

- [ ] 스웨거 작성
  - 확인 필요합니다. 스웨거 작성법을 익히고 있는데 아직 어렵네요

2021-07-14 00:52 UTC, Yubron commented on server/routers/userRouter.js
> +    res.send({ token: token });
현재 로직에는 억세스토큰이랑 리프레쉬토큰에 대한 구분이 없습니다. 그래도 굳이 구분하자면
저기서 넘어가는 토큰은 억세스 토큰이라고 보면 될 것 같아요.
그냥 단순히 토큰을 발행하는거 까지에요. 보안상 문제가 될 수 있긴한데 억세스토큰이랑 리프레쉬토큰에 대해서
공부를 좀 더 해보고 코드를 수정할게요

2021-07-14 00:53 UTC, Yubron approved these changes
고생하셨습니다 !

2021-07-15 01:07 UTC, junh0328 approved these changes
수고하셨습니다-

2021-07-15 01:08 UTC, merged