Feature/#44 kakao login
Doong-Ji/cola-map pull request #45
Opened 2021-07-19 15:08 UTC by Yubron

## #44  

## PR 설명
- 카카오 로그인

## 변경된 내용
- 카카오 로그인을 Front 단에서 Back 단으로 이동

## 추가적인 정보
- 일단 백단 내에서는 올바르게 동작하는 것 같습니다. 근데 이걸 이제 프론트 단으로 넘겨줘야 하는데
 혹시 코드 보시고 방법이 생각나시면 말씀해주시면 감사할거같아요 혼자서 생각해보는 것보다
 프론트 분들이랑 같이 얘기를 하는게 좋을거같아서요 (혼자서는 사실 어케 해야할지 잘 모르겠네요 😂😂)
 
 추가된 npm package 가 있어서 npm install 후 
 colamap/server/config/dev.env 파일 내에
```
KAKAO_KEY=본인 restapi key
KAKAO_REDIRECT_URL=http://localhost:5000/user/kakao/callback
```
추가 후 localhost:5000/user/kakao/login url 로 들어가면 테스트 해보실 수 있어요
 

close #44

2021-07-20 00:52 UTC, dode777 commented
테스트 시에
https://developers.kakao.com/console/app/592835/product/login
위 카카오 Developer 홈페이지에서
Redirect URL 을 `http://localhost:5000/user/kakao/callback` 이렇게 생성해주는 과정도 필요할 것 같네요!

> ![image](https://user-images.githubusercontent.com/61088391/126245841-3a63f0bf-fa45-4e93-9950-20691ce174ae.png)

2021-07-21 01:35 UTC, dode777 requested changes

2021-07-21 02:59 UTC, dode777 commented on server/routers/userRouter.js
> +        code: req.query.code,
로그인 기능을 블로그에 정리하고 있는데 궁금한 게 있어서 여쭤봅니다! 😢

카카오 문서를 보면
파라미터 이름이 redirect_uri로 되어있는데 redirectUri로 설정해줘도 되는 건가요?

![image](https://user-images.githubusercontent.com/61088391/126423368-fb247559-97ed-41cb-b8a5-3035b050444f.png)

2021-07-21 03:09 UTC, junh0328 commented on front/src/index.js
> +    // 여기서 /user > / 로 바꿔보세요!
이 부분은 진수님이랑 작업할 때 'localhost:5000/user' 라우터로 잘 넘어오는 지 프론트에서 확인하기 위한 작업이였습니다 ㅎㅎ 후에는 그냥 'localhost:5000' 으로 보낼 것 같아요!

2021-07-21 03:12 UTC, dode777 commented on front/src/index.js
> +    // 여기서 /user > / 로 바꿔보세요!
음.. 그래도 머지되기 전에는 바꿔줘야 하지 않나요?
저도 일단 로컬에서 `/`로 바꿔서 돌려보고 있습니다!

2021-07-21 07:32 UTC, junh0328 commented on server/routers/userRouter.js
> +  const kakaoAuthURL = `https://kauth.kakao.com/oauth/authorize?client_id=${process.env.KAKAO_KEY}&redirect_uri=${process.env.KAKAO_REDIRECT_URL}&response_type=code&scope=profile_nickname,profile_ima
백엔드 부분에 도해님이 올려주신 비즈니스앱? 그쪽으로 scope가 지금 나눠져 있어서 임시로 주석처리해서 추가하였습니다. 제가 제 부분을 주석처리를 하다는 걸 제 부분을 그대로 커밋하고, 진수님 도해님 부분을 주석처리했네요 ㅜ

2021-07-21 07:32 UTC, junh0328 commented on front/src/sagas/personal.js
> +    localStorage.removeItem('nickname');
로그아웃 또는 로컬 스토리지에 저장된 토큰들을 지움으로써 가능하게 하였는데, 이따 의견 부탁드립니다

2021-07-21 07:32 UTC, junh0328 commented on front/src/pages/Main/index.js
> +        localStorage.setItem('nickname', me.user.profile_nickname);
이렇게 
`localhost:5000/`
을 통해 받은 token 과 user 정보를 구조분해 할당으로 나눠서 각각 키 값을 가지는 객체로 로컬스토리지에 저장하였습니다.

2021-07-21 12:40 UTC, Yubron commented on front/src/sagas/personal.js
> +    localStorage.removeItem('nickname');
넵 이게 맞는건지는 잘 모르겠지만 현재 로직상에는 이러한 방식도 가능한 방법이라 생각합니다.

2021-07-21 13:04 UTC, junh0328 approved these changes

2021-07-21 13:59 UTC, dode777 submitted a review, later dismissed
일단 정상적으로 구현은 된 것 같아요
추가적으로 수정할 부분이 있다면
새로 이슈 만들어서 진행해도 될 것 같습니다!

2021-07-21 23:42 UTC, dode777 submitted a review, later dismissed
고생하셨습니다!

2021-07-22 00:44 UTC, junh0328 approved these changes

2021-07-22 01:01 UTC, junh0328 submitted a review, later dismissed

2021-07-22 02:17 UTC, junh0328 approved these changes

2021-07-23 06:52 UTC, closed without merging