feat: fix post api to change login and response
Doong-Ji/cola-map pull request #62
Opened 2021-07-26 14:01 UTC by Yubron

## #61 

## PR 설명
- 제보 POST 요청 후 Response 값 반환 
- 제보 POST request 값 동일하게 수정

## 변경된 내용
- Store 모델 중 storeName 컬럼을 unique 하지 않도록 변경 ( 중복되는 이름을 가진 식당이 있을 것 같고 kakaoId로 구분가능 )
- 제보 POST 요청 후 Response 값 반환  ( 기존에는 message: success 라는 response 값 전송 )
- 제보 POST request 값 동일하게 수정 ( 기존에는 store의 존재유무에 따라 request 값이 달랐음 )

## 추가적인 정보

closed #61

2021-07-26 14:03 UTC, junh0328 approved these changes
슬랙 통해서 대화 나눴던 내용이라 따로 리뷰할 것은 없네요 수고하셨습니다 😁

2021-07-26 14:26 UTC, dode777 commented on server/routers/postRouter.js
> +    });
`kakaoId`와 `req.user(로그인 된 유저)`로 count를 세면
store가 존재하지만 내가 등록하지 않았을 때도 is_posted가 0으로 뜨지 않나요?

2021-07-26 14:50 UTC, Yubron commented on server/routers/postRouter.js
> +    });
넵넵! is_posted 가 0으로 뜹니다 음... 근데 0으로 떠야 정상적인 범위라고 생각하고 개발했어요.
0이면 등록이 가능한 상태 ( 해당 store 에 해당 user 가 제보를 한번도 한적이 없다. )
1이면 이미 등록한 업체 ( 해당 store 에 해당 user 가 이전에 제보를 했었다. 한 store 에 유저가 여러번 제보 할 수 없다 라고 가정. 왜냐하면 한명이 한 업체를 100번 거짓으로 제보하면 곤란함.. )

2021-07-26 15:08 UTC, dode777 commented on server/routers/postRouter.js
> +    });
아아 제가 store 모델에서 찾는거랑 헷갈렸던 것 같아요
```javascript
await Store.countDocuments({})
```

그게 아니더라도 이 부분은 전혀 생각을 못하고 있었네요.. 
![image](https://user-images.githubusercontent.com/61088391/127012605-d2052fa6-79fa-409b-bea5-22a0ad90bb73.png)

감사합니다!

2021-07-26 15:19 UTC, dode777 approved these changes
고생하셨습니다!

코멘트만 한번 확인 부탁드립니다!

2021-07-26 15:34 UTC, dode777 commented on server/routers/postRouter.js
>      }
`GET /post/store/:storeId` 에서는 post 가 배열 안에 담겨 있고
`POST /post` 에서는 배열 없이 전달되는데

그거는 괜찮나요? 따로 change review 달아 놓진 않았는데
```javascript
post[0]._id
post._id
```
이런 식으로 값을 가져오는 게 조금은 달라질 것 같아요

슬랙에도 같은 내용으로 올려놓긴 했습니다.

2021-07-26 23:27 UTC, junh0328 commented on server/routers/postRouter.js
>      }
저도 확인했는데 그렇긴 하네요 ㅋㅋㅋ 아예 다 post거나 posts가 되는게 맞는 것 같습니다

2021-07-26 23:52 UTC, dode777 commented on server/routers/postRouter.js
>      }
@junh0328 키가 다른 건 말씀해주셔서 알았네요ㅋㅋ

배열 부분은 괜찮나요?

2021-07-27 00:06 UTC, dode777 requested changes
60-72 라인에 대한 코멘트 반영이 필요해보입니다!

2021-07-27 02:18 UTC, Yubron commented on server/routers/postRouter.js
>        });
아아 죄송합니다 앞으로 prettier 사용해서 해볼게요 !

2021-07-27 02:25 UTC, Yubron commented on server/routers/postRouter.js
> +    });
악... 제가 알기로 일단 예시 2개는 동일한 로직으로 알고 있습니다.
```
const a = await Model.create({ })
```
와
```
const b = await Model.find({});
b.name: 'change_name';
b.save();
```
의 차이는 있는데, 익숙한 방법을 쓰다보니 교차해서 사용한거같네요. 사실 로직상은 상관없을텐데
하나로 통일하는게 좋아보이네요 ㅜㅜ 코드리뷰 감사합니다.

2021-07-27 02:27 UTC, dode777 approved these changes
고생하셨습니다!

2021-07-27 02:27 UTC, merged